# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExcelTransformer(object):
    def setupUi(self, ExcelTransformer):
        ExcelTransformer.setObjectName("ExcelTransformer")
        ExcelTransformer.resize(711, 762)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ExcelTransformer)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 651, 751))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.openFile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openFile.setObjectName("openFile")
        self.verticalLayout.addWidget(self.openFile)
        self.saveFile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveFile.setObjectName("saveFile")
        self.verticalLayout.addWidget(self.saveFile)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.ckBoxes = QtWidgets.QVBoxLayout()
        self.ckBoxes.setObjectName("ckBoxes")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.ckBoxes.addWidget(self.label)
        self.horizontalLayout.addLayout(self.ckBoxes)

        self.retranslateUi(ExcelTransformer)
        QtCore.QMetaObject.connectSlotsByName(ExcelTransformer)

    def retranslateUi(self, ExcelTransformer):
        _translate = QtCore.QCoreApplication.translate
        ExcelTransformer.setWindowTitle(_translate("ExcelTransformer", "ExcelTransformer"))
        self.openFile.setText(_translate("ExcelTransformer", "開啟檔案"))
        self.saveFile.setText(_translate("ExcelTransformer", "輸出檔案"))
        self.label.setText(_translate("ExcelTransformer", "Empty"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExcelTransformer = QtWidgets.QWidget()
    ui = Ui_ExcelTransformer()
    ui.setupUi(ExcelTransformer)
    ExcelTransformer.show()
    sys.exit(app.exec_())
